remote_theme: just-the-docs/just-the-docs

title: Python G-Cubed Model
baseurl: "/g-cubed_teaching_model" # the subpath of your site, e.g. /blog
url: "https://lucid-wei.github.io"

permalink: /:title/


# External navigation links
nav_external_links:
  - title: Python API documentation
    url: https://lucid-wei.github.io/g-cubed_teaching_model/docs/gcubed/
    hide_icon: true
  - title: G-Cubed official website
    url: https://www.gcubed.com/
  - title: Page maintainer
    url: mailto:lucid.wei@alumni.anu.edu.au


# Aux links for the upper right navigation
aux_links:
  "GitHub repository":
    - "https://github.com/lucid-wei/g-cubed_teaching_model"
aux_links_new_tab: true

source: docs

back_to_top: true
back_to_top_text: "Back to top"

# logo: "/docs/assets/images/g-cubed-logo.jpg"
